version: "0.1"
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    command: redis-server
    volumes:
      - cache:/data
  database:
    image: mysql/mysql-server:8.0.23
    ports:
      - "3306:3306"
    container_name: taskdatabase
    volumes:
      - db_data:/var/lib/mysql
      - .:/myapp
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
      MYSQL_USER: user_testdb
      MYSQL_PASSWORD: password
  web:
    build: .
    environment:
      DB_USERNAME: user_testdb
      DB_PASSWORD: password
      DB_HOST: database
      REDIS_URL: "redis://redis:6379/0"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
        - database
        - cache
        - sidekiq
    links:
        - cache
  sidekiq:
    build: .
    environment:
      DB_USERNAME: user_testdb
      DB_PASSWORD: password
      DB_HOST: database
      REDIS_URL: "redis://redis:6379/0"
    links:
        - cache
    command: bash -c "bundle exec sidekiq"
    volumes:
      - .:/myapp
    depends_on:
        - database
        - cache

volumes:
  db_data:
  cache:
