default: &default
  host: <%= ENV["DB_HOST"] || "127.0.0.1" %>
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_general_ci
  reconnect: true
  pool: <%= ENV["DB_POOL"] || 30 %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>

development:
  <<: *default
  database: rebuild_boardpackage_development
  host: localhost
  username: root
  password:
  port: 3306
  timeout: 5000


test:
  <<: *default
  database: task_test
  username: <%= ENV["DB_USERNAME"] || "root" %>
  password: <%= ENV["DB_PASSWORD"] || "" %>
